// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiA5rXhFeD5kr51xWQ3px93EXPD1eyJgc',
    appId: '1:639396291897:web:3063388f1e0d3e999a74e8',
    messagingSenderId: '639396291897',
    projectId: 'ecommece-b4422',
    authDomain: 'ecommece-b4422.firebaseapp.com',
    databaseURL: 'https://ecommece-b4422.firebaseio.com',
    storageBucket: 'ecommece-b4422.appspot.com',
    measurementId: 'G-NQNXPVWFN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo7Xj-YZqV0zJpZlB5phHiwWvN8aIjYFE',
    appId: '1:639396291897:android:a2f26fd64da067139a74e8',
    messagingSenderId: '639396291897',
    projectId: 'ecommece-b4422',
    databaseURL: 'https://ecommece-b4422.firebaseio.com',
    storageBucket: 'ecommece-b4422.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqIoPcMBlnjYFpY7wNd9fCzq0d5q8FyHs',
    appId: '1:639396291897:ios:e54531febebefd849a74e8',
    messagingSenderId: '639396291897',
    projectId: 'ecommece-b4422',
    databaseURL: 'https://ecommece-b4422.firebaseio.com',
    storageBucket: 'ecommece-b4422.appspot.com',
    iosBundleId: 'com.example.cafee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqIoPcMBlnjYFpY7wNd9fCzq0d5q8FyHs',
    appId: '1:639396291897:ios:e54531febebefd849a74e8',
    messagingSenderId: '639396291897',
    projectId: 'ecommece-b4422',
    databaseURL: 'https://ecommece-b4422.firebaseio.com',
    storageBucket: 'ecommece-b4422.appspot.com',
    iosBundleId: 'com.example.cafee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiA5rXhFeD5kr51xWQ3px93EXPD1eyJgc',
    appId: '1:639396291897:web:b8e930f587cbc4129a74e8',
    messagingSenderId: '639396291897',
    projectId: 'ecommece-b4422',
    authDomain: 'ecommece-b4422.firebaseapp.com',
    databaseURL: 'https://ecommece-b4422.firebaseio.com',
    storageBucket: 'ecommece-b4422.appspot.com',
    measurementId: 'G-9K1NN3FVSZ',
  );
}
