// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Vx5CldVIT0kw_SxyUhHtTaeI70czY-g',
    appId: '1:826595152760:web:b1aeb20158de93a48bae8d',
    messagingSenderId: '826595152760',
    projectId: 'united-sandbox-416019',
    authDomain: 'united-sandbox-416019.firebaseapp.com',
    storageBucket: 'united-sandbox-416019.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcqvvNyKG0h4Vnt8bfceksWORyz6WZcLs',
    appId: '1:826595152760:android:2ac29f21aac7729e8bae8d',
    messagingSenderId: '826595152760',
    projectId: 'united-sandbox-416019',
    storageBucket: 'united-sandbox-416019.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjV-x8Eq7p_rkIp7Q4gbu3oS8LtSAciBI',
    appId: '1:826595152760:ios:a979fb3f6a213b598bae8d',
    messagingSenderId: '826595152760',
    projectId: 'united-sandbox-416019',
    storageBucket: 'united-sandbox-416019.firebasestorage.app',
    iosBundleId: 'com.example.cafee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjV-x8Eq7p_rkIp7Q4gbu3oS8LtSAciBI',
    appId: '1:826595152760:ios:a979fb3f6a213b598bae8d',
    messagingSenderId: '826595152760',
    projectId: 'united-sandbox-416019',
    storageBucket: 'united-sandbox-416019.firebasestorage.app',
    iosBundleId: 'com.example.cafee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0Vx5CldVIT0kw_SxyUhHtTaeI70czY-g',
    appId: '1:826595152760:web:38144130da5600238bae8d',
    messagingSenderId: '826595152760',
    projectId: 'united-sandbox-416019',
    authDomain: 'united-sandbox-416019.firebaseapp.com',
    storageBucket: 'united-sandbox-416019.firebasestorage.app',
  );

}